name: Setup Data Pipeline Tools
description: >
  Installs runtime dependencies (DuckDB, tippecanoe, libssl) and optionally
  the Rust toolchain + build cache. Set install-rust to false when using
  pre-built binaries from an earlier build job.

inputs:
  install-rust:
    description: Whether to install Rust toolchain and build cache (set false when using pre-built binaries)
    required: false
    default: 'true'
  rust-cache-key:
    description: Additional cache key suffix for Rust build cache (only used when install-rust is true)
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Rust toolchain
      if: inputs.install-rust == 'true'
      uses: dtolnay/rust-toolchain@stable

    - name: Rust build cache
      if: inputs.install-rust == 'true'
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ inputs.rust-cache-key }}

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends cmake libssl-dev pkg-config

    - name: Cache DuckDB native library
      id: cache-duckdb
      uses: actions/cache@v4
      with:
        path: ~/duckdb-lib
        key: duckdb-linux-amd64-v1.4.4

    - name: Install DuckDB native library
      if: steps.cache-duckdb.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget -q https://github.com/duckdb/duckdb/releases/download/v1.4.4/libduckdb-linux-amd64.zip
        mkdir -p ~/duckdb-lib
        unzip -o libduckdb-linux-amd64.zip -d ~/duckdb-lib

    - name: Set DuckDB environment variables
      shell: bash
      run: |
        echo "DUCKDB_LIB_DIR=$HOME/duckdb-lib" >> "$GITHUB_ENV"
        echo "DUCKDB_INCLUDE_DIR=$HOME/duckdb-lib" >> "$GITHUB_ENV"
        echo "LD_LIBRARY_PATH=$HOME/duckdb-lib" >> "$GITHUB_ENV"

    - name: Cache tippecanoe + tile-join
      id: cache-tippecanoe
      uses: actions/cache@v4
      with:
        path: ~/tools
        key: tippecanoe-tile-join-v2-linux-amd64

    - name: Install tippecanoe + tile-join
      if: steps.cache-tippecanoe.outputs.cache-hit != 'true'
      shell: bash
      run: |
        git clone --depth 1 https://github.com/felt/tippecanoe.git /tmp/tippecanoe
        make -j$(nproc) -C /tmp/tippecanoe
        mkdir -p ~/tools
        cp /tmp/tippecanoe/tippecanoe ~/tools/tippecanoe
        cp /tmp/tippecanoe/tile-join ~/tools/tile-join
        rm -rf /tmp/tippecanoe

    - name: Add tools to PATH
      shell: bash
      run: echo "$HOME/tools" >> "$GITHUB_PATH"
